enable_k_anonymity: false
number_of_chunks: 1
chunk_name: BeneficiaryData.csv
output_path: generalized_chunk1.csv
output_directory: pipelineOutput
key_directory: keys
log_file: log.txt
save_output: true
suppress: [FULLNAMEENGLISH, HEAD_MEMBERNAME]
pseudonymize: []
encrypt: [MEMEBERSLNO, URN, MEMBERID, UIDREFERENCENUMBER, HEAD_MEMBERID]
